[package]
name = "rust-http"
version = "0.1.0"
edition = "2021"
authors = ["Lucas Cerqueira"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[workspace]